spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springprojectmysql
    username: root
    password: 19032006
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
springdoc:
   pathsToMatch: /**/**
   swagger-ui:
     use-root-path: true