cors:
  originPatterns: http://localhost:8080,https://lucio.com.br,http://localhost:3000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springprojectmysql
    username: root
    password: 19032006
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
   pathsToMatch: /**/**
   swagger-ui:
     use-root-path: true