name: Continuous Integration with GitHub actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub

      uses: docker/login-action@v3.3.0
      with:
    # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
    # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    
              
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./ws-sts/Spring_MySQL_RestAPI
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./ws-sts
      run: docker compose build

    - name: Push to Docker Hub Container Registry
      run: 
         docker tag ${{ secrets.DOCKER_USERNAME }}/springprojectmysql:latest ${{ secrets.DOCKER_USERNAME }}/springprojectmysql:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/springprojectmysql:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/springprojectmysql:latest

      
